SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PLAYER_SPEED = 3

BULLET_SPEED = 8
BULLET_SIZE = 6
SHOOT_COOLDOWN = 200

ENEMY_SPEED = 1.2
ENEMY_SIZE = 24
ENEMY_SPAWN_INTERVAL = 1200
ENEMY_SPAWN_PADDING = 160


ENEMY_PATH_UPDATE_INTERVAL = 200
SHOW_ENEMY_PATHS = True
