services:
  multiplayer-server:
    build: .
    container_name: multiplayer-server
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.multiplayer.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.multiplayer.entrypoints=ws"
      - "traefik.tcp.routers.multiplayer.service=multiplayer"
      - "traefik.tcp.services.multiplayer.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true