name: Build multiplayer server

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./multiplayer/server
        run: |
          docker build -t ghcr.io/lsc-jh/top-down-shooter/multiplayer-server:latest .
          docker push ghcr.io/lsc-jh/top-down-shooter/multiplayer-server:latest